### ISSUE TITLE
Where to find a copy of the code?

### ISSUE THREAD

**Issue by wdelfuego** [BlackbitDigitalCommerce/pimcore-cms-toolbox#1]
I'm looking for a free copy of this GPL licensed bundle. Unfortunately this repository doesn't seem to contain any code, just documentation.

Does anyone have access to it?

**Comment by BlackbitDevs** [comment]
The CMS Toolbox bundle is licensed under GPLv3 but it is not free. Please see https://shop.blackbit.com/pimcore-cms-toolbox/ to buy it.

**Comment by wdelfuego** [comment]
Sure but since it's GPL licensed, anyone who has access to it has the right (not the obligation) to distribute it for free to the rest of us. That's why I'm asking.
